project:
  title: "techdoc"
  render:
    - SystemDesignProjection.qmd
    - SystemOperationsProjection.qmd
    - SystemOperationsLighting.qmd 
    - SystemOperationsVideo.qmd
    - SystemDesignVideo.qmd
    - SystemDesignAudio.qmd
    - SystemDesignYouth.qmd
    - SystemDesignDante.qmd
  output-dir: _output
    
date-format: "[Last Update] MMM DD YYYY HH:mm:ss"

toc: true
number-sections: true

format:
  html:
    author: "UAC Media Arts"
    date: last-modified
    css: styles.css
    html-math-method: katex
    toc-depth: 2
    toc-location: right
    number-sections: true
  pdf:
    author: "UAC Media Arts"
    date: last-modified
    documentclass: report
    margin-left: 25mm
    margin-right: 25mm
    lot: true
    lof: true
    toc: true
    toc-depth: 2 
    number-sections: true 
    fig-pos: h
    header-includes:
       \usepackage{float} 
