
```{r fipackages}
require(kableExtra)
require(readxl)
require(dplyr)
```

```{r fidata}
path <-"~/Documents/UACTech/SystemDocumentation"
inventoryfile <- "TechInventory.xlsx"
fname <- paste(path, inventoryfile, sep="/")
further <- read_excel(fname, sheet = "Further")
```

# Further Information

There are several types of documents available.

```{r}
chart <- tribble(
  ~Type, ~Description,
"System Operations Documents",
"These documents will tell you how to operate each subsystem.",

"System Design Documents",
"These provide a deep dive into where all components are located, how they are wired, how they are configured, and why. A regular operator does not normally need to know this level of detail - until there is a problem.",

"Administration Documents",  
"This will contain information that very few people will need to know and is mostly related to credentials (accounts, userids, and passwords), and what you need to know to manage those." ,

"Manuals",
"These are publications from the manufactures of the equipment we have."
)

chart |>
 	   gt() |>  
		opt_stylize(style = 3) |>
	    opt_row_striping(  row_striping = TRUE) |>
		tab_style( style = cell_text( 	weight = "bold",  	),
		        	locations = cells_body(  	columns = "Type") )  
```

There is an operations and a design guide for each of the major subsystems.  

```{r fifurther, asis=FALSE}
further %>%
  mutate (Operations = ifelse(is.na(Operations),"",text_spec("X", link=Operations))) %>%
  mutate (Design = ifelse(is.na(Design),"",text_spec("X", link=Design))) %>%
  mutate (Other = ifelse(is.na(Other),"",text_spec("X", link=Other))) %>%

  kable( escape = FALSE) %>%
  column_spec( 1 , bold = TRUE ) %>%
  kable_styling("striped" )

make_hyperlink = function(myurl,mytext=myurl) {
  paste('<a href="',myurl,'">',mytext,'</a>')
}

further %>%
  mutate (Operations = ifelse(is.na(Operations),"",text_spec("X", link=Operations))) %>%
  mutate (Design = ifelse(is.na(Design),"",text_spec("X", link=Design))) %>%
  mutate (Other = ifelse(is.na(Other),"",text_spec("X", link=Other))) |>
	   gt() |>  
		opt_stylize(style = 3) |>
	    opt_row_striping(  row_striping = TRUE) |>
		tab_style( style = cell_text( 	weight = "bold",  	),
		        	locations = cells_body(  	columns = "Topic") )    |>
 	  fmt (
     columns = 'Operations',
     fns = make_hyperlink)
```