---
title: "System Design - Dante"
author: "Terry Doner"
date: last-modified
format:
  html:
    toc: true
    toc-loction: top
    number-sections: true
    theme: cosmo
  pdf:
    toc: true
    number-sections: true
execute:
  echo:    false
  warning: false
  message: false
  eval:    true
---

```{r options, include=FALSE}
options(knitr.table.format = "html") # latex for pdf 
```

```{r packages}
source("commonPackages.R")

require(here)
require(xml2)
```

```{r functions}
source("commonFunctions.R")
source("commonFunctionsAudio.R")
```

```{r getdata}
NetworkInventory <- get.network()
Tech_Inventory   <- get.inventory()
```

[Back to top](#top)

<p style="page-break-before: always"></p>
# Configuration

The descriptions of the configurations will generally start at the input side of the system and work towards the outputs. A high level overview is shown here @fig-dante-overview

```{dot}
//| fig-width: 6
//| label: fig-dante-overview
//| fig-cap: "Overview of the Audio System"
//| file: sda-overview.gv
```

[Back to top](#top) 

# Dante Output Dump

```{r dod}
o1 <- work.config.consoleoutputs
o2 <- work.config.dantepatch

do <- "ZAKU-0001"

merge(o1, o2) %>%
  arrange(NetworkDeviceOut, NetworkDeviceChannelOut) %>%
  mutate(Sent.To = glue("{NetworkDeviceIn}:   {NetworkDeviceChannelIn}")) %>% 
  mutate(Sent.From = glue("{NetworkDeviceOut}:{NetworkDeviceChannelOut}")) %>%
  select(Output, Sent.From, Label, Usage, 
         Sent.To
         ) %>%
  kable(caption=glue("Dante Outputs for {do}"))  %>%
    kable_styling(bootstrap_options = c("striped", "hover"))
```

```{r}
require(xml2)
fname <- "/Users/donert/Dropbox/UAC_Audio/Dante-2023-04-09-normal.xml"

dc <- read_xml(fname)
preset_name <- xml_text(xml_find_all(dc, "//preset/name"))
model_list  <- xml_text(xml_find_all(dc, "//device/model_name"))
device_list <- xml_text(xml_find_all(dc, "//device/name"))
```

```{r}
cap <- glue("Devices in Preset {preset_name}")

data.frame(device_name = device_list, model_name=model_list) %>%
	kable(caption=cap) %>%
	kable_classic()
```

