---
title: "System Design Fellowship Hall"
date: last-modified
editor: visual
execute: 
  eval: TRUE
  echo: false
  warning: false
  message: false

format:
  html:
    toc: true
  pdf:
    toc: true
  titlepage-pdf:
    toc: true     

always_allow_html: yes  
---

# Introduction

This is a detailed design report for the Audio and Video systems in Fellowship Hall. This documents is not complete as a lot of mapping work remains.

Notes for future updates.

-   Speakers and cables
-   

```{r packages_functions }
source('commonPackages.R')
source('commonFunctions.R')
source('commonDiagram.R')
```

```{r get_data}
inventory <- get.inventory()  |>  
	filter(   Building == 'Main'  
			& Floor    == 'Basement'  
		    & Room     %in% c( 'FellowshipHall', 'Electrical')) |>
	filter(  Disposition == 'N') |>
	filter(!is.na(Building) ) 

			
cables <- get.cables()
```

# Audio Diagram

::: {#fig-audio-inputs .cell-output-display}
```{r audio_diag, results="asis"}
label <- "'Audio '"

targets <- c(  'CDWU-A001'   
			 , "2401-2800" # audio extractor
			 , "2401-3001" # hdmi-sdi
			 , "2401-3003" # mixer
			 , "2401-3100", "2401-3101" # Speakers
			 ) 
xd <- c() 
dot_code <- get_diagram(targets, inventory, cables
						, label=label , exc_dev=xd )
out_str <- get_diagram_aux(dot_code)
cat(out_str)

```
```{r audio_devices}
inventory |>
	filter(AssetTag %in% targets) |>
	select(AssetTag, Manufacturer, Model, Desc) |>
	gt() |> 
	opt_stylize(style=3) |>
	tab_header("Audio Devices")
```

```{r audio_cables}
x <- targets
cables |> 
	filter(SrcTag %in% x | DstTag %in% x  ) |> 
	select(-Invoice, -GraphFormula, -`Labelled?`) |>
	arrange(SrcTag, DstTag) |>
	gt() |> 
	opt_stylize(style=3) |>
	tab_header("Audio Cables")
```
 

# Video System Diagram

::: {#fig-video-system .cell-output-display}
```{r video_digram, results="asis" }
targets <- c(  'CDWU-A001'
            , '2401-3001'
            , '2401-3002'  
			, "2401-3004"
			, "1704-0100", 
			"2401-3012" #bluray
            )
 
xd <- c( )
dot_code <- get_diagram(targets, inventory, cables
						, label="'Video System'"
						, exc_dev=xd)
out_str <- get_diagram_aux(dot_code)
cat(out_str)
```

```{r video_devices}
inventory |>
	filter(AssetTag %in% targets) |>
	select(AssetTag, Manufacturer, Model, Desc) |>
	gt() |> 
	opt_stylize(style=3) |>
	tab_header("Video Devices")

```

```{r video_cables}
x <- targets
cables |> 
	filter(SrcTag %in% x | DstTag %in% x  ) |> 
	select(-Invoice, -GraphFormula, -`Labelled?`) |>
	arrange(SrcTag, DstTag) |>
	gt() |> 
	opt_stylize(style=3) |>
	tab_header("Video Cables")
```

{{< pagebreak >}}

# Network Diagram

::: {#fig-network .cell-output-display}
```{r network_digram, results="asis", eval=FALSE}
targets <- c(   "NSCU-A002"
,"CDWU-A001")
 
dot_code <- get_diagram(targets, inventory, cables, label="'Network System'")
out_str <- get_diagram_aux(dot_code)
cat(out_str)
```

Network
:::

{{< pagebreak >}}

# Audio Inventory

```{r audio_inventory}
#| label: tbl-audio_inventory
#| tbl-cap: Audio Inventory
#| tbl-cap-location: bottom

asset_items <- inventory |> 
	arrange(AssetTag) |>
	select(AssetTag, SN, Manufacturer, Model, Type, Location, Desc) 

nr <- nrow(asset_items)
mhdr <- glue("Installed Audio Devices  ")
shdr <- glue("n={nr}")

asset_items |>
	gt() |>
			opt_stylize(style = 3) |>
	tab_header( glue("Audio Inventory ")
			   
			  )   |>
	tab_style(
		style=list( cell_text(weight = "bold") ),
		locations=cells_body(columns=AssetTag)
	) |>
	tab_header(mhdr, subtitle = shdr) |>
	sub_missing(missing_text="")
```

```{r audio_cables2}

cable_items <- cables |>
	filter(SrcTag %in% asset_items$AssetTag | DstTag %in% asset_items$AssetTag) |>
	filter(!is.na(SrcTag) & !is.na(DstTag))

nr <- nrow(cable_items)
mhdr <- glue("Installed Audio Cables ")
shdr <- glue("n={nr}")

cable_items |>
	arrange(Tag) |>
	select(Tag, SrcTag, SrcPort, DstTag, DstPort, Type, Usage, Notes) |>
	gt() |>
	opt_stylize(style=3) |>
	tab_header(mhdr, subtitle = shdr) |>
	sub_missing(missing_text="")

```

{{< pagebreak >}}

# Item Inventory

```{r item_inventory}
#| label: tbl-item_inventory
#| tbl-cap: Item Inventory
#| tbl-cap-location: bottom

asset_items <- inventory |>
	filter(  Building == 'Main' 
		   & Room     == 'FellowshipHall' 
		   ) |> 
    arrange(AssetTag) |>
	select(AssetTag, Category ,Location, SN, Manufacturer, Model, Type, Desc) 

nr <- nrow(asset_items )
mhdr <- glue("Installed Items (excluding cables)")
shdr <- glue("n={nr}") 

asset_items |>
	gt() |>
	opt_stylize(style = 3) |>
	tab_header( mhdr, subtitle = shdr  )   |>
	tab_style(
		style=list( cell_text(weight = "bold") ),
		locations=cells_body(columns=AssetTag)
	)
```

```{r installed_cables}
cable_items <- cables |>
	filter(SrcTag %in% asset_items$AssetTag | DstTag %in% asset_items$AssetTag) |>
	filter(!is.na(SrcTag) & !is.na(DstTag))

nr <- nrow(cable_items)
mhdr <- glue("Installed Cables ")
shdr <- glue("n={nr}")

cable_items |>
	arrange(Tag) |>
	select(Tag, SrcTag, SrcPort, DstTag, DstPort, Type, Usage, Notes) |>
	gt() |>
	opt_stylize(style=3) |>
	tab_header(mhdr, subtitle = shdr) |>
	sub_missing(missing_text="")
```

{{< include common_trailer.qmd >}}

