---
title: "System Design - Dante"
author: "Terry Doner"
date: "`r Sys.setenv(TZ= 'Canada/Eastern' ); format(Sys.time(), '%B %d %Y %H:%M %p')`"
output:
  html_document:
    toc: yes
    number_sections: true
    theme: cosmo
---

```{r options, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message=FALSE)
options(knitr.table.format = "html") # latex for pdf 
```

```{r packages}
source("commonPackages.R")

require(here)
require(xml2)
```

```{r functions}
source("commonFunctions.R")
source("commonFunctionsAudio.R")
```

```{r getdata}
NetworkInventory <- get.network()
Tech_Inventory   <- get.inventory()
```

[Back to top](#top)

<p style="page-break-before: always"></p>
# Configuration

The descriptions of the configurations will generally start at the input side of the system and work towards the outputs.

```{r overview}
DiagrammeR::grViz("sda-overview.gv")
```

[Back to top](#top) 

# Dante Output Dump

```{r dod}
o1 <- work.config.consoleoutputs
o2 <- work.config.dantepatch

do <- "ZAKU-0001"

merge(o1, o2) %>%
  arrange(NetworkDeviceOut, NetworkDeviceChannelOut) %>%
  mutate(Sent.To = glue("{NetworkDeviceIn}:   {NetworkDeviceChannelIn}")) %>% 
  mutate(Sent.From = glue("{NetworkDeviceOut}:{NetworkDeviceChannelOut}")) %>%
  select(Output, Sent.From, Label, Usage, 
         Sent.To
         ) %>%
  kable(caption=glue("Dante Outputs for {do}"))  %>%
    kable_styling(bootstrap_options = c("striped", "hover"))
```

```{r}
fname <- "/Users/donert/Dropbox/UAC_Audio/Dante-2020-10-25.xml"

dc <- read_xml(fname)

preset.name <- xml_find_all(dc, "/preset/name") %>% xml_contents()


xfa <- xml_find_all(dc, "//device")

xa <- xml_attrs(xfa)

# bind the data.frames built in the iterator together
br <- bind_rows(lapply(xml_find_all(dc, "//device"), function(x) {

  # extract the attributes from the parent tag as a data.frame
  parent <- data.frame(as.list(xml_attrs(x)), stringsAsFactors=FALSE)

  # make a data.frame out of the attributes of the kids
  #kids <- bind_rows(lapply(xml_children(x), function(x) as.list(xml_attrs(x))))

  # combine them
  #cbind.data.frame(parent, kids, stringsAsFactors=FALSE)

}))
```

