---
title: "System Design Youth"
date: last-modified
editor: visual
execute: 
  eval: TRUE
  echo: false
  warning: false
  message: false

format:
  html:
    toc: true
  pdf:
    toc: true

always_allow_html: yes  
---

# Introduction

This is a detailed design report for the Audio and Video systems in the Youth Building. This documents is not complete as a lot of mapping work remains.

```{r packages_functions }
source('commonPackages.R')
source('commonFunctions.R')
source('commonDiagram.R')
```

```{r get_data}
inventory <- get.inventory()  
cables <- get.cables()
```

# Audio Inputs Diagram

::: {#fig-audio-inputs .cell-output-display}
```{r audio_inputs, results="asis"}
label <- "'Audio inputs'"

targets <- c('2308-0906','ZAKU-A001', 'CDWU-A002', '2308-0914')
dot_code <- get_diagram(targets, inventory, cables, label=label)
out_str <- get_diagram_aux(dot_code)
cat(out_str)

```

Audio Inputs
:::

# Audio Ouputs Diagram

::: {#fig-audio-outputs .cell-output-display}
```{r audio_out, results="asis" }
targets <- c( 'ZAKU-A001',  '2308-0008', '2308-0913', '2308-0912', '2308-0911'
			, '2308-0910', '2308-0909', '2308-0908', '2308-0904', '2308-0903'
			, '2308-0902' , '2308-1000')

label <- "'Audio Outputs'"

dot_code <- get_diagram(targets, inventory, cables, label=label)
out_str <- get_diagram_aux(dot_code)
cat(out_str)
```

Audio Outputs
:::

```{dot}
//| label: fig-sdy-audio-outputs4
//| fig-cap: "Audio system simplified"
//| file: sdy-audio-outputs4.gv
```

# Video System Diagram

::: cell-output-display
```{r video_digram, results="asis"}
targets <- c( 'ZAKU-A001' 
			,  'CDWU-A002'
, '2308-0002'
, '2308-0003'  
, "2309-1600", "2309-1601")
 
dot_code <- get_diagram(targets, inventory, cables, label="'Video System'")
out_str <- get_diagram_aux(dot_code)
cat(out_str)
```

Video System
:::

# Audio Inventory

```{r audio_inventory}
#| label: tbl-audio_inventory
#| tbl-cap: Audio Inventory
#| tbl-cap-location: bottom

inventory |>
	filter(Category == 'Audio'
		   & Building == 'Portable' 
		   & Disposition == 'N') |> 
	filter(!is.na(Building) ) |>
	arrange(AssetTag) |>
	select(AssetTag, SN, Manufacturer, Model, Location, Desc) |>
	gt() |>
			opt_stylize(style = 3) |>
	tab_header( glue("Audio Inventory ")
			   
			  )   |>
	tab_style(
		style=list( cell_text(weight = "bold") ),
		locations=cells_body(columns=AssetTag)
	)
```

# Video Inventory

```{r video_inventory}
#| label: tbl-video_inventory
#| tbl-cap: Video Inventory
#| tbl-cap-location: bottom

inventory |>
	filter(Category == 'Video'
		   & Building == 'Portable' 
		   & Disposition == 'N') |> 
	filter(!is.na(Building) ) |>
	select(AssetTag, SN, Manufacturer, Model, Desc) |>
	gt() |>
			opt_stylize(style = 3) |>
	tab_header( glue("Video Inventory ")
			   
			  )   |>
	tab_style(
		style=list( cell_text(weight = "bold") ),
		locations=cells_body(columns=AssetTag)
	)
```

```{r}
targets <- "2308-0008"
target_devices <- targets
```

```{r gt_cables, eval=FALSE}
target_cables |>	
		select(-GraphFormula) |>
	gt() |>
			opt_stylize(style = 3) |>
	tab_header( glue("Cables connected to {paste(target, collapse=', ')}") 
			  , subtitle = "They are highlighted in yellow"
			   ) |>
    tab_style(
      style = list(
        cell_fill(color = "yellow")
        ),
      locations = cells_body(
        columns = SrcTag ,
        rows = SrcTag %in% target
    )
  )|>
    tab_style(
      style = list(
        cell_fill(color = "yellow") 
        ),
      locations = cells_body(
        columns = DstTag ,
        rows = DstTag %in% target
    )
  ) |>
	tab_style(
		style=list( cell_text(weight = "bold") ),
		locations=cells_body(columns=Tag)
	)  
```
